name: spam2000
namespace: spam2000

image:
  repository: andriiuni/spam2000
  tag: 1.1394.355

replicas: 2

containerPort: 3000

service:
  port: 80

env:
  requestRate: "10"

resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "300m"
